
source_name := wordle_guesser

all:
	# cd $(source_name)/ && cargo build --release --bin wordle_guesser
	# cp $(source_name)/target/release/$(source_name) client

	cp $(source_name)/$(source_name) client
